// src/main/services/license.service.ts
// Asymmetric RSA-2048 license validation.
// The application ONLY holds the Public Key.
// Tokens are generated offline by the developer via scripts/generate-license.js

import { createVerify } from 'crypto'
import * as fs from 'fs'
import * as path from 'path'
import { app } from 'electron'
import { getMachineId } from './machineId.service'

// ─── Embedded RSA-2048 Public Key ───────────────────────────────────────────
// PKCS#1 PEM — generated by scripts/generate-keys.js
const PUBLIC_KEY_PEM = `-----BEGIN RSA PUBLIC KEY-----
MIIBCgKCAQEAroxUcE8/7QOHXXsZxMxSVXp2xvzUS10u5MTqIdK2bfffF0IQ9YrG
p8ahXhWKDpF8PwAAx/Emn/g5QBGwuIRvX4t5P4d3kaZ1tBOG00WO/bTxb5kXY3kU
oGCtdxLRgLgWNxfcYJi8VZ9BV0orHccD330ydivCU7nQfR40g418j33EuJAoJBil
y666GXzXE5B4saM1Ul/+Pxh25R1nNPotStlX3NP8A7ihIgaU9H2tpGtJt1meFROA
8mS4HzhUTL0jauyQDYdKfSTeKAKIfWVTqhvTT62mMB9bTOvMFLvagL1nWYtWkN05
IwAft6O5rySENi/jZPXThXRqlblEdpZWuQIDAQAB
-----END RSA PUBLIC KEY-----`

// ─── Types ────────────────────────────────────────────────────────────────
export type LicenseType = 'PERPETUAL' | 'ANNUAL'

export interface LicensePayload {
  machineId: string
  clientName: string
  issuedAt: string // ISO date string
  licenseType: LicenseType
  expiresAt?: string // Optional: ISO date string for ANNUAL
}

export interface LicenseStatus {
  isActivated: boolean
  machineId: string
  clientName?: string
  licenseType?: LicenseType
  issuedAt?: string
  expiresAt?: string
  daysRemaining?: number
  error?: string
}

// ─── License file path ─────────────────────────────────────────────────────
function getLicenseFilePath(): string {
  return path.join(app.getPath('userData'), 'license.key')
}

// ─── Token format: base64url(JSON_payload).base64url(RSA_signature) ───────
function base64UrlDecode(str: string): Buffer {
  // base64url → base64
  const padded = str.replace(/-/g, '+').replace(/_/g, '/') + '==='.slice((str.length % 4 || 4) - 1)
  return Buffer.from(padded, 'base64')
}

/** Verify a license token cryptographically */
function verifyToken(token: string): { valid: boolean; payload?: LicensePayload; error?: string } {
  try {
    const parts = token.trim().split('.')
    if (parts.length !== 2) return { valid: false, error: 'تنسيق الرمز غير صالح' }

    const [payloadB64, signatureB64] = parts
    const payloadBuffer = base64UrlDecode(payloadB64)
    const signature = base64UrlDecode(signatureB64)

    // Verify RSA-SHA256 signature
    const verifier = createVerify('RSA-SHA256')
    verifier.update(payloadBuffer)
    const isValid = verifier.verify(
      { key: PUBLIC_KEY_PEM, format: 'pem', type: 'pkcs1' },
      signature
    )

    if (!isValid) return { valid: false, error: 'التوقيع الرقمي غير صحيح' }

    const payload: LicensePayload = JSON.parse(payloadBuffer.toString('utf8'))
    return { valid: true, payload }
  } catch (e) {
    return { valid: false, error: 'خطأ في فك تشفير الرخصة' }
  }
}

/** Check ANNUAL license expiry */
function checkExpiry(payload: LicensePayload): { expired: boolean; daysRemaining: number } {
  if (payload.licenseType !== 'ANNUAL') return { expired: false, daysRemaining: Infinity }

  const issued = new Date(payload.issuedAt)
  const expiry = payload.expiresAt ? new Date(payload.expiresAt) : new Date(issued.getTime() + 365 * 24 * 3600 * 1000)
  const now = new Date()
  const msRemaining = expiry.getTime() - now.getTime()
  const daysRemaining = Math.ceil(msRemaining / (24 * 3600 * 1000))
  return { expired: daysRemaining <= 0, daysRemaining: Math.max(0, daysRemaining) }
}

// ─── Public API ────────────────────────────────────────────────────────────

/** Validate and activate a license token. Writes license.key on success. */
export function activateLicense(token: string): LicenseStatus {
  const currentMachineId = getMachineId()
  const { valid, payload, error } = verifyToken(token)

  if (!valid || !payload) {
    return { isActivated: false, machineId: currentMachineId, error: error ?? 'رمز غير صالح' }
  }

  // Verify Machine ID matches this hardware
  if (payload.machineId !== currentMachineId) {
    return {
      isActivated: false,
      machineId: currentMachineId,
      error: `هذه الرخصة مسجلة لجهاز مختلف (${payload.machineId})`
    }
  }

  // Save the valid token to disk
  try {
    fs.writeFileSync(getLicenseFilePath(), token.trim(), 'utf8')
  } catch (e) {
    return { isActivated: false, machineId: currentMachineId, error: 'فشل حفظ ملف الترخيص' }
  }

  const { daysRemaining } = checkExpiry(payload)

  return {
    isActivated: true,
    machineId: currentMachineId,
    clientName: payload.clientName,
    licenseType: payload.licenseType,
    issuedAt: payload.issuedAt,
    expiresAt: payload.expiresAt,
    daysRemaining: daysRemaining === Infinity ? undefined : daysRemaining
  }
}

/** Read the stored license and return current status. Called on every app start. */
export function getLicenseStatus(): LicenseStatus {
  const currentMachineId = getMachineId()
  const licensePath = getLicenseFilePath()

  if (!fs.existsSync(licensePath)) {
    return { isActivated: false, machineId: currentMachineId }
  }

  let token: string
  try {
    token = fs.readFileSync(licensePath, 'utf8').trim()
  } catch {
    return { isActivated: false, machineId: currentMachineId, error: 'فشل قراءة ملف الترخيص' }
  }

  const { valid, payload, error } = verifyToken(token)

  if (!valid || !payload) {
    return { isActivated: false, machineId: currentMachineId, error }
  }

  if (payload.machineId !== currentMachineId) {
    return {
      isActivated: false,
      machineId: currentMachineId,
      error: 'هذه الرخصة مسجلة لجهاز مختلف'
    }
  }

  const { daysRemaining } = checkExpiry(payload)

  return {
    isActivated: true,
    machineId: currentMachineId,
    clientName: payload.clientName,
    licenseType: payload.licenseType,
    issuedAt: payload.issuedAt,
    expiresAt: payload.expiresAt,
    daysRemaining: daysRemaining === Infinity ? undefined : daysRemaining
  }
}

/** Singleton cached status — refreshed only when explicitly requested */
let _cachedStatus: LicenseStatus | null = null

export function getCachedLicenseStatus(): LicenseStatus {
  if (!_cachedStatus) {
    _cachedStatus = getLicenseStatus()
  }
  return _cachedStatus
}

export function invalidateLicenseCache(): void {
  _cachedStatus = null
}

/** Convenience: returns true if the app has a valid active license */
export function isLicensed(): boolean {
  return getCachedLicenseStatus().isActivated
}
